name: Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 0 * * *'

jobs:
  generic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: install dependencies
        run: npm install
      - name: run checkup
        run: node ./scripts/checkup.js
        env:
          PROXY_URL: ${{ secrets.PROXY_URL }}
      - name: publish changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add ./dist -f
          git add -A
          git commit -m "chore($GITHUB_RUN_ID): push new files"
          git push